name: Bug Report
description: File a bug report
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        The `#drake` posts on [StackOverflow](https://stackoverflow.com/questions/tagged/drake) also might help you find a solution.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of Drake are you using?
      value: Unknown
  - type: dropdown
    attributes:
      label: What operating system are you using?
      multiple: true
      options:
        - Unknown / Other
        - Ubuntu 20.04
        - Ubuntu 22.04
        - macOS 11 (Big Sur)
        - macOS 12 (Monterey)
        - Other
  - type: dropdown
    attributes:
      label: What installation option are you using?
      multiple: true
      options:
        - Unknown / Other
        - pip install drake
        - apt install drake
        - binary tar.gz download
        - dockerhub
        - compiled from source code using CMake
        - compiled from source code using Bazel
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
